/*------------------------------------------------------------------------------------------------*/
/*                                                                                                */
/*           Copyright (C) 2016 Brite Semiconductor Co., Ltd. All rights reserved.                */
/*                                                                                                */
/*------------------------------------------------------------------------------------------------*/
#ifndef __CDL_DDR_H__
#define __CDL_DDR_H__
#include "cdl_pll.h"
#define DDR_DEBUG_ENABLE
#ifdef  DDR_DEBUG_ENABLE
#define ddr_info	debug
#else
#define ddr_info
#endif

#define BSTLEN8
#define DDR_CTRL_BASE	0xC1C00000
#define DDR_PHY_BASE	(DDR_CTRL_BASE + 0x400)
#define DDR_BASE		0x40000000

#define DDR_PLL_CFG			0x00000008
#define DDR_CONTROL       	0x00000050
//#define RNG_LATCH2DDR     	0x00000004
//#define DDR_PLL_CFG_REG   	0x00000008

#include "./lpddr_inc/lpddr_CTL_100_cl3_bl8.h"
#include "./lpddr_inc/lpddr_CTL_133_cl3_bl4.h"
#include "./lpddr_inc/lpddr_CTL_133_cl3_bl8.h"
#include "./lpddr_inc/lpddr_CTL_200_cl3_bl4.h"
#include "./lpddr_inc/lpddr_CTL_200_cl3_bl8.h"
#include "./lpddr_inc/lpddr_PHY_100_cl3_bl8.h"
#include "./lpddr_inc/lpddr_PHY_133_cl3_bl4.h"
#include "./lpddr_inc/lpddr_PHY_133_cl3_bl8.h"
#include "./lpddr_inc/lpddr_PHY_200_cl3_bl4.h"
#include "./lpddr_inc/lpddr_PHY_200_cl3_bl8.h"

#include "./lpddr2_inc/lpddr2_CTL_133_cl3_bl4.h"
#include "./lpddr2_inc/lpddr2_CTL_133_cl3_bl8.h"
#include "./lpddr2_inc/lpddr2_CTL_200_cl3_bl4.h"
#include "./lpddr2_inc/lpddr2_CTL_200_cl3_bl8.h"
#include "./lpddr2_inc/lpddr2_CTL_400_cl6_bl4.h"
#include "./lpddr2_inc/lpddr2_CTL_400_cl6_bl8.h"
#include "./lpddr2_inc/lpddr2_CTL_533_cl8_bl4.h"
#include "./lpddr2_inc/lpddr2_CTL_533_cl8_bl8.h"
#include "./lpddr2_inc/lpddr2_PHY_133_cl3_bl4.h"
#include "./lpddr2_inc/lpddr2_PHY_133_cl3_bl8.h"
#include "./lpddr2_inc/lpddr2_PHY_200_cl3_bl4.h"
#include "./lpddr2_inc/lpddr2_PHY_200_cl3_bl8.h"
#include "./lpddr2_inc/lpddr2_PHY_400_cl6_bl4.h"
#include "./lpddr2_inc/lpddr2_PHY_400_cl6_bl8.h"
#include "./lpddr2_inc/lpddr2_PHY_533_cl8_bl4.h"
#include "./lpddr2_inc/lpddr2_PHY_533_cl8_bl8.h"

/*************************************************************************************************************/
// macro definition
/*************************************************************************************************************/
#define TRNG_CTRL 0x0
#define TRNG_MODE 0x4
#define TRNG_SMODE 0x8
#define TRNG_STAT 0xc
#define TRNG_IE 0x10
#define TRNG_ISTAT 0x14
#define TRNG_RAND0 0x24
#define TRNG_RAND1 0x28
#define TRNG_RAND2 0x2C
#define TRNG_RAND3 0x30
#define CMD_GEN_NOISE 0x1
#define CMD_CREATE_STATE 0x3
#define CMD_GEN_RANDOM 0x6
#define DDR_SCRAM_UPDATE 0x1C0

//=============================================
//  Register FIELD/OFFSET/WIDTH
//=============================================
#define ADDR_CMP_EN_ADDR               96                   
#define ADDR_CMP_EN_OFFSET             24                   
#define ADDR_CMP_EN_WIDTH              1                    
#define ADDR_COLLISION_MPM_DIS_ADDR    97                   
#define ADDR_COLLISION_MPM_DIS_OFFSET  0                    
#define ADDR_COLLISION_MPM_DIS_WIDTH   1                    
#define ADDR_SPACE_ADDR                72                   
#define ADDR_SPACE_OFFSET              24                   
#define ADDR_SPACE_WIDTH               6                    
#define AGE_COUNT_ADDR                 96                   
#define AGE_COUNT_OFFSET               8                    
#define AGE_COUNT_WIDTH                8                    
#define AP_ADDR                        26                   
#define AP_OFFSET                      24                   
#define AP_WIDTH                       1                    
#define APREBIT_ADDR                   96                   
#define APREBIT_OFFSET                 0                    
#define APREBIT_WIDTH                  4                    
#define AREFRESH_ADDR                  29                   
#define AREFRESH_OFFSET                16                   
#define AREFRESH_WIDTH                 1                    
#define ASYNC_CDC_STAGES_ADDR          2                    
#define ASYNC_CDC_STAGES_OFFSET        8                    
#define ASYNC_CDC_STAGES_WIDTH         8                    
#define AUTO_REFRESH_MODE_ADDR         29                   
#define AUTO_REFRESH_MODE_OFFSET       24                   
#define AUTO_REFRESH_MODE_WIDTH        1                    
#define AUTO_TEMPCHK_VAL_ADDR          60                   
#define AUTO_TEMPCHK_VAL_OFFSET        16                   
#define AUTO_TEMPCHK_VAL_WIDTH         8                    
#define AXI0_CMDFIFO_LOG2_DEPTH_ADDR   2                    
#define AXI0_CMDFIFO_LOG2_DEPTH_OFFSET 16                   
#define AXI0_CMDFIFO_LOG2_DEPTH_WIDTH  8                    
#define AXI0_FIFO_TYPE_REG_ADDR        133                  
#define AXI0_FIFO_TYPE_REG_OFFSET      8                    
#define AXI0_FIFO_TYPE_REG_WIDTH       2                    
#define AXI0_FIXED_PORT_PRIORITY_ENABLE_ADDR 132                  
#define AXI0_FIXED_PORT_PRIORITY_ENABLE_OFFSET 16                   
#define AXI0_FIXED_PORT_PRIORITY_ENABLE_WIDTH 1                    
#define AXI0_RDFIFO_LOG2_DEPTH_ADDR    2                    
#define AXI0_RDFIFO_LOG2_DEPTH_OFFSET  24                   
#define AXI0_RDFIFO_LOG2_DEPTH_WIDTH   8                    
#define AXI0_R_PRIORITY_ADDR           132                  
#define AXI0_R_PRIORITY_OFFSET         24                   
#define AXI0_R_PRIORITY_WIDTH          4                    
#define AXI0_TRANS_WRFIFO_LOG2_DEPTH_ADDR 3                    
#define AXI0_TRANS_WRFIFO_LOG2_DEPTH_OFFSET 8                    
#define AXI0_TRANS_WRFIFO_LOG2_DEPTH_WIDTH 8                    
#define AXI0_WRCMD_PROC_FIFO_LOG2_DEPTH_ADDR 3                    
#define AXI0_WRCMD_PROC_FIFO_LOG2_DEPTH_OFFSET 16                   
#define AXI0_WRCMD_PROC_FIFO_LOG2_DEPTH_WIDTH 8                    
#define AXI0_WR_ARRAY_LOG2_DEPTH_ADDR  3                    
#define AXI0_WR_ARRAY_LOG2_DEPTH_OFFSET 0                    
#define AXI0_WR_ARRAY_LOG2_DEPTH_WIDTH 8                    
#define AXI0_W_PRIORITY_ADDR           133                  
#define AXI0_W_PRIORITY_OFFSET         0                    
#define AXI0_W_PRIORITY_WIDTH          4                    
#define BANK_ADDR_INTLV_EN_ADDR        95                   
#define BANK_ADDR_INTLV_EN_OFFSET      24                   
#define BANK_ADDR_INTLV_EN_WIDTH       1                    
#define BANK_DIFF_0_ADDR               92                   
#define BANK_DIFF_0_OFFSET             0                    
#define BANK_DIFF_0_WIDTH              2                    
#define BANK_DIFF_1_ADDR               92                   
#define BANK_DIFF_1_OFFSET             8                    
#define BANK_DIFF_1_WIDTH              2                    
#define BANK_SPLIT_EN_ADDR             97                   
#define BANK_SPLIT_EN_OFFSET           8                    
#define BANK_SPLIT_EN_WIDTH            1                    
#define BANK_START_BIT_ADDR            95                   
#define BANK_START_BIT_OFFSET          16                   
#define BANK_START_BIT_WIDTH           5                    
#define BIST_ADDR_CHECK_ADDR           73                   
#define BIST_ADDR_CHECK_OFFSET         8                    
#define BIST_ADDR_CHECK_WIDTH          1                    
#define BIST_DATA_CHECK_ADDR           73                   
#define BIST_DATA_CHECK_OFFSET         0                    
#define BIST_DATA_CHECK_WIDTH          1                    
#define BIST_DATA_MASK_ADDR            76                   
#define BIST_DATA_MASK_OFFSET          0                    
#define BIST_DATA_MASK_WIDTH           64                   
#define BIST_DATA_PATTERN_ADDR         79                   
#define BIST_DATA_PATTERN_OFFSET       0                    
#define BIST_DATA_PATTERN_WIDTH        128                  
#define BIST_ERR_COUNT_ADDR            84                   
#define BIST_ERR_COUNT_OFFSET          0                    
#define BIST_ERR_COUNT_WIDTH           12                   
#define BIST_ERR_STOP_ADDR             83                   
#define BIST_ERR_STOP_OFFSET           16                   
#define BIST_ERR_STOP_WIDTH            12                   
#define BIST_EXP_DATA_ADDR             110                  
#define BIST_EXP_DATA_OFFSET           0                    
#define BIST_EXP_DATA_WIDTH            128                  
#define BIST_FAIL_ADDR_ADDR            118                  
#define BIST_FAIL_ADDR_OFFSET          0                    
#define BIST_FAIL_ADDR_WIDTH           34                   
#define BIST_FAIL_DATA_ADDR            114                  
#define BIST_FAIL_DATA_OFFSET          0                    
#define BIST_FAIL_DATA_WIDTH           128                  
#define BIST_GO_ADDR                   72                   
#define BIST_GO_OFFSET                 8                    
#define BIST_GO_WIDTH                  1                    
#define BIST_RESULT_ADDR               72                   
#define BIST_RESULT_OFFSET             16                   
#define BIST_RESULT_WIDTH              2                    
#define BIST_RET_STATE_ADDR            83                   
#define BIST_RET_STATE_OFFSET          8                    
#define BIST_RET_STATE_WIDTH           1                    
#define BIST_RET_STATE_EXIT_ADDR       83                   
#define BIST_RET_STATE_EXIT_OFFSET     0                    
#define BIST_RET_STATE_EXIT_WIDTH      1                    
#define BIST_START_ADDRESS_ADDR        74                   
#define BIST_START_ADDRESS_OFFSET      0                    
#define BIST_START_ADDRESS_WIDTH       34                   
#define BIST_TEST_MODE_ADDR            78                   
#define BIST_TEST_MODE_OFFSET          0                    
#define BIST_TEST_MODE_WIDTH           3                    
#define BSTLEN_ADDR                    28                   
#define BSTLEN_OFFSET                  0                    
#define BSTLEN_WIDTH                   3                    
#define CASLAT_LIN_F0_ADDR             13                   
#define CASLAT_LIN_F0_OFFSET           0                    
#define CASLAT_LIN_F0_WIDTH            5                    
#define CASLAT_LIN_F1_ADDR             13                   
#define CASLAT_LIN_F1_OFFSET           16                   
#define CASLAT_LIN_F1_WIDTH            5                    
#define CKE_DELAY_ADDR                 37                   
#define CKE_DELAY_OFFSET               8                    
#define CKE_DELAY_WIDTH                3                    
#define CKE_STATUS_ADDR                133                  
#define CKE_STATUS_OFFSET              16                   
#define CKE_STATUS_WIDTH               2                    
#define CKSRE_F0_ADDR                  37                   
#define CKSRE_F0_OFFSET                24                   
#define CKSRE_F0_WIDTH                 8                    
#define CKSRE_F1_ADDR                  38                   
#define CKSRE_F1_OFFSET                8                    
#define CKSRE_F1_WIDTH                 8                    
#define CKSRX_F0_ADDR                  38                   
#define CKSRX_F0_OFFSET                0                    
#define CKSRX_F0_WIDTH                 8                    
#define CKSRX_F1_ADDR                  38                   
#define CKSRX_F1_OFFSET                16                   
#define CKSRX_F1_WIDTH                 8                    
#define COL_DIFF_0_ADDR                93                   
#define COL_DIFF_0_OFFSET              0                    
#define COL_DIFF_0_WIDTH               4                    
#define COL_DIFF_1_ADDR                93                   
#define COL_DIFF_1_OFFSET              8                    
#define COL_DIFF_1_WIDTH               4                    
#define COMMAND_AGE_COUNT_ADDR         96                   
#define COMMAND_AGE_COUNT_OFFSET       16                   
#define COMMAND_AGE_COUNT_WIDTH        8                    
#define CONCURRENTAP_ADDR              27                   
#define CONCURRENTAP_OFFSET            0                    
#define CONCURRENTAP_WIDTH             1                    
#define CONTROLLER_BUSY_ADDR           101                  
#define CONTROLLER_BUSY_OFFSET         24                   
#define CONTROLLER_BUSY_WIDTH          1                    
#define CS0_IDLE_ADDR                  48                   
#define CS0_IDLE_OFFSET                0                    
#define CS0_IDLE_WIDTH                 1                    
#define CS1_IDLE_ADDR                  48                   
#define CS1_IDLE_OFFSET                8                    
#define CS1_IDLE_WIDTH                 1                    
#define CS_MAP_ADDR                    100                  
#define CS_MAP_OFFSET                  8                    
#define CS_MAP_WIDTH                   2                    
#define CS_MSK_0_ADDR                  94                   
#define CS_MSK_0_OFFSET                16                   
#define CS_MSK_0_WIDTH                 16                   
#define CS_MSK_1_ADDR                  95                   
#define CS_MSK_1_OFFSET                0                    
#define CS_MSK_1_WIDTH                 16                   
#define CS_SAME_EN_ADDR                98                   
#define CS_SAME_EN_OFFSET              16                   
#define CS_SAME_EN_WIDTH               1                    
#define CS_VAL_0_ADDR                  93                   
#define CS_VAL_0_OFFSET                16                   
#define CS_VAL_0_WIDTH                 16                   
#define CS_VAL_1_ADDR                  94                   
#define CS_VAL_1_OFFSET                0                    
#define CS_VAL_1_WIDTH                 16                   
#define CTRLUPD_REQ_ADDR               102                  
#define CTRLUPD_REQ_OFFSET             0                    
#define CTRLUPD_REQ_WIDTH              1                    
#define CTRLUPD_REQ_PER_AREF_EN_ADDR   102                  
#define CTRLUPD_REQ_PER_AREF_EN_OFFSET 8                    
#define CTRLUPD_REQ_PER_AREF_EN_WIDTH  1                    
#define CURRENT_REG_COPY_ADDR          53                   
#define CURRENT_REG_COPY_OFFSET        16                   
#define CURRENT_REG_COPY_WIDTH         1                    
#define DFI_ERROR_ADDR                 102                  
#define DFI_ERROR_OFFSET               16                   
#define DFI_ERROR_WIDTH                5                    
#define DFI_ERROR_INFO_ADDR            103                  
#define DFI_ERROR_INFO_OFFSET          0                    
#define DFI_ERROR_INFO_WIDTH           20                   
#define DFI_PHY_RDLVL_GATE_MODE_ADDR   130                  
#define DFI_PHY_RDLVL_GATE_MODE_OFFSET 0                    
#define DFI_PHY_RDLVL_GATE_MODE_WIDTH  1                    
#define DFI_PHY_RDLVL_MODE_ADDR        129                  
#define DFI_PHY_RDLVL_MODE_OFFSET      24                   
#define DFI_PHY_RDLVL_MODE_WIDTH       1                    
#define DFS_PHY_REG_WRITE_ADDR_ADDR    54                   
#define DFS_PHY_REG_WRITE_ADDR_OFFSET  0                    
#define DFS_PHY_REG_WRITE_ADDR_WIDTH   32                   
#define DFS_PHY_REG_WRITE_DATA_F0_ADDR 55                   
#define DFS_PHY_REG_WRITE_DATA_F0_OFFSET 0                    
#define DFS_PHY_REG_WRITE_DATA_F0_WIDTH 32                   
#define DFS_PHY_REG_WRITE_DATA_F1_ADDR 56                   
#define DFS_PHY_REG_WRITE_DATA_F1_OFFSET 0                    
#define DFS_PHY_REG_WRITE_DATA_F1_WIDTH 32                   
#define DFS_PHY_REG_WRITE_EN_ADDR      53                   
#define DFS_PHY_REG_WRITE_EN_OFFSET    24                   
#define DFS_PHY_REG_WRITE_EN_WIDTH     1                    
#define DFS_PHY_REG_WRITE_MASK_ADDR    57                   
#define DFS_PHY_REG_WRITE_MASK_OFFSET  0                    
#define DFS_PHY_REG_WRITE_MASK_WIDTH   4                    
#define DFS_PHY_REG_WRITE_WAIT_ADDR    57                   
#define DFS_PHY_REG_WRITE_WAIT_OFFSET  8                    
#define DFS_PHY_REG_WRITE_WAIT_WIDTH   16                   
#define DISABLE_RD_INTERLEAVE_ADDR     99                   
#define DISABLE_RD_INTERLEAVE_OFFSET   24                   
#define DISABLE_RD_INTERLEAVE_WIDTH    1                    
#define DISABLE_RW_GROUP_W_BNK_CONFLICT_ADDR 99                   
#define DISABLE_RW_GROUP_W_BNK_CONFLICT_OFFSET 0                    
#define DISABLE_RW_GROUP_W_BNK_CONFLICT_WIDTH 2                    
#define DLL_RST_ADJ_DLY_ADDR           134                  
#define DLL_RST_ADJ_DLY_OFFSET         16                   
#define DLL_RST_ADJ_DLY_WIDTH          8                    
#define DLL_RST_DELAY_ADDR             134                  
#define DLL_RST_DELAY_OFFSET           0                    
#define DLL_RST_DELAY_WIDTH            16                   
#define DRAM_CLASS_ADDR                0                    
#define DRAM_CLASS_OFFSET              8                    
#define DRAM_CLASS_WIDTH               4                    
#define DRAM_CLK_DISABLE_ADDR          136                  
#define DRAM_CLK_DISABLE_OFFSET        0                    
#define DRAM_CLK_DISABLE_WIDTH         2                    
#define ENABLE_QUICK_SREFRESH_ADDR     37                   
#define ENABLE_QUICK_SREFRESH_OFFSET   0                    
#define ENABLE_QUICK_SREFRESH_WIDTH    1                    
#define EN_1T_TIMING_ADDR              155                  
#define EN_1T_TIMING_OFFSET            0                    
#define EN_1T_TIMING_WIDTH             1                    
#define FREQ_CHANGE_ENABLE_ADDR        51                   
#define FREQ_CHANGE_ENABLE_OFFSET      16                   
#define FREQ_CHANGE_ENABLE_WIDTH       1                    
#define GATHER_FIFO_RESYNC_ADDR        103                  
#define GATHER_FIFO_RESYNC_OFFSET      24                   
#define GATHER_FIFO_RESYNC_WIDTH       1                    
#define INHIBIT_DRAM_CMD_ADDR          100                  
#define INHIBIT_DRAM_CMD_OFFSET        0                    
#define INHIBIT_DRAM_CMD_WIDTH         2                    
#define INITAREF_ADDR                  12                   
#define INITAREF_OFFSET                0                    
#define INITAREF_WIDTH                 4                    
#define INT_ACK_ADDR                   105                  
#define INT_ACK_OFFSET                 0                    
#define INT_ACK_WIDTH                  26                   
#define INT_MASK_ADDR                  106                  
#define INT_MASK_OFFSET                0                    
#define INT_MASK_WIDTH                 27                   
#define INT_STATUS_ADDR                104                  
#define INT_STATUS_OFFSET              0                    
#define INT_STATUS_WIDTH               27                   
#define IN_ORDER_ACCEPT_ADDR           101                  
#define IN_ORDER_ACCEPT_OFFSET         8                    
#define IN_ORDER_ACCEPT_WIDTH          1                    
#define LONG_COUNT_MASK_ADDR           84                   
#define LONG_COUNT_MASK_OFFSET         16                   
#define LONG_COUNT_MASK_WIDTH          5                    
#define LOWPOWER_REFRESH_ENABLE_ADDR   37                   
#define LOWPOWER_REFRESH_ENABLE_OFFSET 16                   
#define LOWPOWER_REFRESH_ENABLE_WIDTH  2                    
#define LPDDR2_S4_ADDR                 100                  
#define LPDDR2_S4_OFFSET               24                   
#define LPDDR2_S4_WIDTH                1                    
#define LPI_DPD_WAKEUP_F0_ADDR         40                   
#define LPI_DPD_WAKEUP_F0_OFFSET       8                    
#define LPI_DPD_WAKEUP_F0_WIDTH        4                    
#define LPI_DPD_WAKEUP_F1_ADDR         41                   
#define LPI_DPD_WAKEUP_F1_OFFSET       16                   
#define LPI_DPD_WAKEUP_F1_WIDTH        4                    
#define LPI_PD_WAKEUP_F0_ADDR          39                   
#define LPI_PD_WAKEUP_F0_OFFSET        16                   
#define LPI_PD_WAKEUP_F0_WIDTH         4                    
#define LPI_PD_WAKEUP_F1_ADDR          40                   
#define LPI_PD_WAKEUP_F1_OFFSET        24                   
#define LPI_PD_WAKEUP_F1_WIDTH         4                    
#define LPI_SR_MCCLK_GATE_WAKEUP_F0_ADDR 40                   
#define LPI_SR_MCCLK_GATE_WAKEUP_F0_OFFSET 0                    
#define LPI_SR_MCCLK_GATE_WAKEUP_F0_WIDTH 4                    
#define LPI_SR_MCCLK_GATE_WAKEUP_F1_ADDR 41                   
#define LPI_SR_MCCLK_GATE_WAKEUP_F1_OFFSET 8                    
#define LPI_SR_MCCLK_GATE_WAKEUP_F1_WIDTH 4                    
#define LPI_SR_WAKEUP_F0_ADDR          39                   
#define LPI_SR_WAKEUP_F0_OFFSET        24                   
#define LPI_SR_WAKEUP_F0_WIDTH         4                    
#define LPI_SR_WAKEUP_F1_ADDR          41                   
#define LPI_SR_WAKEUP_F1_OFFSET        0                    
#define LPI_SR_WAKEUP_F1_WIDTH         4                    
#define LPI_TIMER_COUNT_ADDR           42                   
#define LPI_TIMER_COUNT_OFFSET         8                    
#define LPI_TIMER_COUNT_WIDTH          12                   
#define LPI_TIMER_WAKEUP_F0_ADDR       40                   
#define LPI_TIMER_WAKEUP_F0_OFFSET     16                   
#define LPI_TIMER_WAKEUP_F0_WIDTH      4                    
#define LPI_TIMER_WAKEUP_F1_ADDR       41                   
#define LPI_TIMER_WAKEUP_F1_OFFSET     24                   
#define LPI_TIMER_WAKEUP_F1_WIDTH      4                    
#define LPI_WAKEUP_EN_ADDR             42                   
#define LPI_WAKEUP_EN_OFFSET           0                    
#define LPI_WAKEUP_EN_WIDTH            5                    
#define LPI_WAKEUP_TIMEOUT_ADDR        43                   
#define LPI_WAKEUP_TIMEOUT_OFFSET      0                    
#define LPI_WAKEUP_TIMEOUT_WIDTH       12                   
#define LP_ARB_STATE_ADDR              44                   
#define LP_ARB_STATE_OFFSET            8                    
#define LP_ARB_STATE_WIDTH             4                    
#define LP_AUTO_ENTRY_EN_ADDR          44                   
#define LP_AUTO_ENTRY_EN_OFFSET        16                   
#define LP_AUTO_ENTRY_EN_WIDTH         3                    
#define LP_AUTO_EXIT_EN_ADDR           44                   
#define LP_AUTO_EXIT_EN_OFFSET         24                   
#define LP_AUTO_EXIT_EN_WIDTH          3                    
#define LP_AUTO_MEM_GATE_EN_ADDR       45                   
#define LP_AUTO_MEM_GATE_EN_OFFSET     0                    
#define LP_AUTO_MEM_GATE_EN_WIDTH      2                    
#define LP_AUTO_PD_IDLE_ADDR           45                   
#define LP_AUTO_PD_IDLE_OFFSET         8                    
#define LP_AUTO_PD_IDLE_WIDTH          12                   
#define LP_AUTO_SR_IDLE_ADDR           45                   
#define LP_AUTO_SR_IDLE_OFFSET         24                   
#define LP_AUTO_SR_IDLE_WIDTH          8                    
#define LP_AUTO_SR_MC_GATE_IDLE_ADDR   46                   
#define LP_AUTO_SR_MC_GATE_IDLE_OFFSET 0                    
#define LP_AUTO_SR_MC_GATE_IDLE_WIDTH  8                    
#define LP_CMD_ADDR                    39                   
#define LP_CMD_OFFSET                  0                    
#define LP_CMD_WIDTH                   9                    
#define LP_CS_ADDR                     47                   
#define LP_CS_OFFSET                   24                   
#define LP_CS_WIDTH                    2                    
#define LP_STATE_CS0_ADDR              43                   
#define LP_STATE_CS0_OFFSET            24                   
#define LP_STATE_CS0_WIDTH             6                    
#define LP_STATE_CS1_ADDR              44                   
#define LP_STATE_CS1_OFFSET            0                    
#define LP_STATE_CS1_WIDTH             6                    
#define MAX_COL_REG_ADDR               1                    
#define MAX_COL_REG_OFFSET             8                    
#define MAX_COL_REG_WIDTH              4                    
#define MAX_CS_REG_ADDR                1                    
#define MAX_CS_REG_OFFSET              16                   
#define MAX_CS_REG_WIDTH               2                    
#define MAX_ROW_REG_ADDR               1                    
#define MAX_ROW_REG_OFFSET             0                    
#define MAX_ROW_REG_WIDTH              5                    
#define MR0_DATA_F0_0_ADDR             61                   
#define MR0_DATA_F0_0_OFFSET           16                   
#define MR0_DATA_F0_0_WIDTH            16                   
#define MR0_DATA_F0_1_ADDR             67                   
#define MR0_DATA_F0_1_OFFSET           0                    
#define MR0_DATA_F0_1_WIDTH            16                   
#define MR0_DATA_F1_0_ADDR             63                   
#define MR0_DATA_F1_0_OFFSET           0                    
#define MR0_DATA_F1_0_WIDTH            16                   
#define MR0_DATA_F1_1_ADDR             68                   
#define MR0_DATA_F1_1_OFFSET           16                   
#define MR0_DATA_F1_1_WIDTH            16                   
#define MR16_DATA_0_ADDR               66                   
#define MR16_DATA_0_OFFSET             8                    
#define MR16_DATA_0_WIDTH              8                    
#define MR16_DATA_1_ADDR               71                   
#define MR16_DATA_1_OFFSET             24                   
#define MR16_DATA_1_WIDTH              8                    
#define MR17_DATA_0_ADDR               66                   
#define MR17_DATA_0_OFFSET             16                   
#define MR17_DATA_0_WIDTH              8                    
#define MR17_DATA_1_ADDR               72                   
#define MR17_DATA_1_OFFSET             0                    
#define MR17_DATA_1_WIDTH              8                    
#define MR1_DATA_F0_0_ADDR             62                   
#define MR1_DATA_F0_0_OFFSET           0                    
#define MR1_DATA_F0_0_WIDTH            16                   
#define MR1_DATA_F0_1_ADDR             67                   
#define MR1_DATA_F0_1_OFFSET           16                   
#define MR1_DATA_F0_1_WIDTH            16                   
#define MR1_DATA_F1_0_ADDR             63                   
#define MR1_DATA_F1_0_OFFSET           16                   
#define MR1_DATA_F1_0_WIDTH            16                   
#define MR1_DATA_F1_1_ADDR             69                   
#define MR1_DATA_F1_1_OFFSET           0                    
#define MR1_DATA_F1_1_WIDTH            16                   
#define MR2_DATA_F0_0_ADDR             62                   
#define MR2_DATA_F0_0_OFFSET           16                   
#define MR2_DATA_F0_0_WIDTH            16                   
#define MR2_DATA_F0_1_ADDR             68                   
#define MR2_DATA_F0_1_OFFSET           0                    
#define MR2_DATA_F0_1_WIDTH            16                   
#define MR2_DATA_F1_0_ADDR             64                   
#define MR2_DATA_F1_0_OFFSET           0                    
#define MR2_DATA_F1_0_WIDTH            16                   
#define MR2_DATA_F1_1_ADDR             69                   
#define MR2_DATA_F1_1_OFFSET           16                   
#define MR2_DATA_F1_1_WIDTH            16                   
#define MR3_DATA_F0_0_ADDR             65                   
#define MR3_DATA_F0_0_OFFSET           0                    
#define MR3_DATA_F0_0_WIDTH            16                   
#define MR3_DATA_F0_1_ADDR             70                   
#define MR3_DATA_F0_1_OFFSET           16                   
#define MR3_DATA_F0_1_WIDTH            16                   
#define MR3_DATA_F1_0_ADDR             65                   
#define MR3_DATA_F1_0_OFFSET           16                   
#define MR3_DATA_F1_0_WIDTH            16                   
#define MR3_DATA_F1_1_ADDR             71                   
#define MR3_DATA_F1_1_OFFSET           0                    
#define MR3_DATA_F1_1_WIDTH            16                   
#define MR8_DATA_0_ADDR                66                   
#define MR8_DATA_0_OFFSET              0                    
#define MR8_DATA_0_WIDTH               8                    
#define MR8_DATA_1_ADDR                71                   
#define MR8_DATA_1_OFFSET              16                   
#define MR8_DATA_1_WIDTH               8                    
#define MRSINGLE_DATA_0_ADDR           64                   
#define MRSINGLE_DATA_0_OFFSET         16                   
#define MRSINGLE_DATA_0_WIDTH          16                   
#define MRSINGLE_DATA_1_ADDR           70                   
#define MRSINGLE_DATA_1_OFFSET         0                    
#define MRSINGLE_DATA_1_WIDTH          16                   
#define MRW_STATUS_ADDR                59                   
#define MRW_STATUS_OFFSET              0                    
#define MRW_STATUS_WIDTH               8                    
#define NO_AUTO_MRR_INIT_ADDR          11                   
#define NO_AUTO_MRR_INIT_OFFSET        24                   
#define NO_AUTO_MRR_INIT_WIDTH         1                    
#define NO_CMD_INIT_ADDR               12                   
#define NO_CMD_INIT_OFFSET             24                   
#define NO_CMD_INIT_WIDTH              1                    
#define NO_ZQ_INIT_ADDR                91                   
#define NO_ZQ_INIT_OFFSET              16                   
#define NO_ZQ_INIT_WIDTH               1                    
#define NUM_Q_ENTRIES_ACT_DISABLE_ADDR 99                   
#define NUM_Q_ENTRIES_ACT_DISABLE_OFFSET 8                    
#define NUM_Q_ENTRIES_ACT_DISABLE_WIDTH 4                    
#define OUT_OF_RANGE_ADDR_ADDR         107                  
#define OUT_OF_RANGE_ADDR_OFFSET       0                    
#define OUT_OF_RANGE_ADDR_WIDTH        34                   
#define OUT_OF_RANGE_LENGTH_ADDR       108                  
#define OUT_OF_RANGE_LENGTH_OFFSET     8                    
#define OUT_OF_RANGE_LENGTH_WIDTH      8                    
#define OUT_OF_RANGE_SOURCE_ID_ADDR    109                  
#define OUT_OF_RANGE_SOURCE_ID_OFFSET  0                    
#define OUT_OF_RANGE_SOURCE_ID_WIDTH   16                   
#define OUT_OF_RANGE_TYPE_ADDR         108                  
#define OUT_OF_RANGE_TYPE_OFFSET       16                   
#define OUT_OF_RANGE_TYPE_WIDTH        7                    
#define PCPCS_CS_MAP_ADDR              47                   
#define PCPCS_CS_MAP_OFFSET            16                   
#define PCPCS_CS_MAP_WIDTH             2                    
#define PCPCS_PD_EN_ADDR               46                   
#define PCPCS_PD_EN_OFFSET             8                    
#define PCPCS_PD_EN_WIDTH              1                    
#define PCPCS_PD_ENTER_DEPTH_ADDR      46                   
#define PCPCS_PD_ENTER_DEPTH_OFFSET    16                   
#define PCPCS_PD_ENTER_DEPTH_WIDTH     4                    
#define PCPCS_PD_ENTER_TIMER_ADDR      47                   
#define PCPCS_PD_ENTER_TIMER_OFFSET    0                    
#define PCPCS_PD_ENTER_TIMER_WIDTH     8                    
#define PCPCS_PD_EXIT_DEPTH_ADDR       46                   
#define PCPCS_PD_EXIT_DEPTH_OFFSET     24                   
#define PCPCS_PD_EXIT_DEPTH_WIDTH      4                    
#define PCPCS_PD_MASK_ADDR             47                   
#define PCPCS_PD_MASK_OFFSET           8                    
#define PCPCS_PD_MASK_WIDTH            2                    
#define PERIPHERAL_MRR_DATA_ADDR       60                   
#define PERIPHERAL_MRR_DATA_OFFSET     0                    
#define PERIPHERAL_MRR_DATA_WIDTH      16                   
#define PLACEMENT_EN_ADDR              97                   
#define PLACEMENT_EN_OFFSET            16                   
#define PLACEMENT_EN_WIDTH             1                    
#define PORT_CMD_ERROR_ADDR_ADDR       120                  
#define PORT_CMD_ERROR_ADDR_OFFSET     0                    
#define PORT_CMD_ERROR_ADDR_WIDTH      34                   
#define PORT_CMD_ERROR_ID_ADDR         121                  
#define PORT_CMD_ERROR_ID_OFFSET       8                    
#define PORT_CMD_ERROR_ID_WIDTH        16                   
#define PORT_CMD_ERROR_TYPE_ADDR       121                  
#define PORT_CMD_ERROR_TYPE_OFFSET     24                   
#define PORT_CMD_ERROR_TYPE_WIDTH      2                    
#define PRIORITY_EN_ADDR               97                   
#define PRIORITY_EN_OFFSET             24                   
#define PRIORITY_EN_WIDTH              1                    
#define PWRDN_SHIFT_DELAY_ADDR         51                   
#define PWRDN_SHIFT_DELAY_OFFSET       8                    
#define PWRDN_SHIFT_DELAY_WIDTH        6                    
#define PWRUP_SREFRESH_EXIT_ADDR       36                   
#define PWRUP_SREFRESH_EXIT_OFFSET     16                   
#define PWRUP_SREFRESH_EXIT_WIDTH      1                    
#define PWRUP_SREFRESH_EXIT_CS_ADDR    51                   
#define PWRUP_SREFRESH_EXIT_CS_OFFSET  0                    
#define PWRUP_SREFRESH_EXIT_CS_WIDTH   2                    
#define Q_FULLNESS_ADDR                101                  
#define Q_FULLNESS_OFFSET              0                    
#define Q_FULLNESS_WIDTH               4                    
#define R2R_DIFFCS_DLY_F0_ADDR         122                  
#define R2R_DIFFCS_DLY_F0_OFFSET       0                    
#define R2R_DIFFCS_DLY_F0_WIDTH        5                    
#define R2R_DIFFCS_DLY_F1_ADDR         123                  
#define R2R_DIFFCS_DLY_F1_OFFSET       0                    
#define R2R_DIFFCS_DLY_F1_WIDTH        5                    
#define R2R_SAMECS_DLY_ADDR            124                  
#define R2R_SAMECS_DLY_OFFSET          0                    
#define R2R_SAMECS_DLY_WIDTH           5                    
#define R2W_DIFFCS_DLY_F0_ADDR         122                  
#define R2W_DIFFCS_DLY_F0_OFFSET       8                    
#define R2W_DIFFCS_DLY_F0_WIDTH        5                    
#define R2W_DIFFCS_DLY_F1_ADDR         123                  
#define R2W_DIFFCS_DLY_F1_OFFSET       8                    
#define R2W_DIFFCS_DLY_F1_WIDTH        5                    
#define R2W_SAMECS_DLY_F0_ADDR         124                  
#define R2W_SAMECS_DLY_F0_OFFSET       8                    
#define R2W_SAMECS_DLY_F0_WIDTH        5                    
#define R2W_SAMECS_DLY_F1_ADDR         124                  
#define R2W_SAMECS_DLY_F1_OFFSET       16                   
#define R2W_SAMECS_DLY_F1_WIDTH        5                    
#define RDLAT_ADJ_F0_ADDR              141                  
#define RDLAT_ADJ_F0_OFFSET            0                    
#define RDLAT_ADJ_F0_WIDTH             5                    
#define RDLAT_ADJ_F1_ADDR              146                  
#define RDLAT_ADJ_F1_OFFSET            0                    
#define RDLAT_ADJ_F1_WIDTH             5                    
#define RDLVL_AREF_EN_ADDR             131                  
#define RDLVL_AREF_EN_OFFSET           8                    
#define RDLVL_AREF_EN_WIDTH            1                    
#define RDLVL_CS_ADDR                  129                  
#define RDLVL_CS_OFFSET                0                    
#define RDLVL_CS_WIDTH                 1                    
#define RDLVL_CS_MAP_ADDR              132                  
#define RDLVL_CS_MAP_OFFSET            0                    
#define RDLVL_CS_MAP_WIDTH             2                    
#define RDLVL_EN_ADDR                  150                  
#define RDLVL_EN_OFFSET                8                    
#define RDLVL_EN_WIDTH                 1                    
#define RDLVL_ERROR_STATUS_ADDR        152                  
#define RDLVL_ERROR_STATUS_OFFSET      0                    
#define RDLVL_ERROR_STATUS_WIDTH       2                    
#define RDLVL_GATE_CS_MAP_ADDR         132                  
#define RDLVL_GATE_CS_MAP_OFFSET       8                    
#define RDLVL_GATE_CS_MAP_WIDTH        2                    
#define RDLVL_GATE_EN_ADDR             150                  
#define RDLVL_GATE_EN_OFFSET           16                   
#define RDLVL_GATE_EN_WIDTH            1                    
#define RDLVL_GATE_INTERVAL_ADDR       153                  
#define RDLVL_GATE_INTERVAL_OFFSET     0                    
#define RDLVL_GATE_INTERVAL_WIDTH      16                   
#define RDLVL_GATE_ON_SREF_EXIT_ADDR   131                  
#define RDLVL_GATE_ON_SREF_EXIT_OFFSET 0                    
#define RDLVL_GATE_ON_SREF_EXIT_WIDTH  1                    
#define RDLVL_GATE_PERIODIC_ADDR       130                  
#define RDLVL_GATE_PERIODIC_OFFSET     24                   
#define RDLVL_GATE_PERIODIC_WIDTH      1                    
#define RDLVL_GATE_REQ_ADDR            128                  
#define RDLVL_GATE_REQ_OFFSET          24                   
#define RDLVL_GATE_REQ_WIDTH           1                    
#define RDLVL_GATE_ROTATE_ADDR         131                  
#define RDLVL_GATE_ROTATE_OFFSET       24                   
#define RDLVL_GATE_ROTATE_WIDTH        1                    
#define RDLVL_GATE_SEQ_EN_ADDR         129                  
#define RDLVL_GATE_SEQ_EN_OFFSET       16                   
#define RDLVL_GATE_SEQ_EN_WIDTH        2                    
#define RDLVL_INTERVAL_ADDR            152                  
#define RDLVL_INTERVAL_OFFSET          8                    
#define RDLVL_INTERVAL_WIDTH           16                   
#define RDLVL_ON_SREF_EXIT_ADDR        130                  
#define RDLVL_ON_SREF_EXIT_OFFSET      16                   
#define RDLVL_ON_SREF_EXIT_WIDTH       1                    
#define RDLVL_PERIODIC_ADDR            130                  
#define RDLVL_PERIODIC_OFFSET          8                    
#define RDLVL_PERIODIC_WIDTH           1                    
#define RDLVL_REQ_ADDR                 128                  
#define RDLVL_REQ_OFFSET               16                   
#define RDLVL_REQ_WIDTH                1                    
#define RDLVL_RESP_MASK_ADDR           150                  
#define RDLVL_RESP_MASK_OFFSET         0                    
#define RDLVL_RESP_MASK_WIDTH          4                    
#define RDLVL_ROTATE_ADDR              131                  
#define RDLVL_ROTATE_OFFSET            16                   
#define RDLVL_ROTATE_WIDTH             1                    
#define RDLVL_SEQ_EN_ADDR              129                  
#define RDLVL_SEQ_EN_OFFSET            8                    
#define RDLVL_SEQ_EN_WIDTH             2                    
#define READ_MODEREG_ADDR              59                   
#define READ_MODEREG_OFFSET            8                    
#define READ_MODEREG_WIDTH             17                   
#define REDUC_ADDR                     100                  
#define REDUC_OFFSET                   16                   
#define REDUC_WIDTH                    1                    
#define REFRESH_PER_AUTO_TEMPCHK_ADDR  61                   
#define REFRESH_PER_AUTO_TEMPCHK_OFFSET 0                    
#define REFRESH_PER_AUTO_TEMPCHK_WIDTH 16                   
#define REG_DIMM_ENABLE_ADDR           29                   
#define REG_DIMM_ENABLE_OFFSET         8                    
#define REG_DIMM_ENABLE_WIDTH          1                    
#define ROW_DIFF_0_ADDR                92                   
#define ROW_DIFF_0_OFFSET              16                   
#define ROW_DIFF_0_WIDTH               3                    
#define ROW_DIFF_1_ADDR                92                   
#define ROW_DIFF_1_OFFSET              24                   
#define ROW_DIFF_1_WIDTH               3                    
#define RW_SAME_EN_ADDR                98                   
#define RW_SAME_EN_OFFSET              0                    
#define RW_SAME_EN_WIDTH               1                    
#define RW_SAME_PAGE_EN_ADDR           98                   
#define RW_SAME_PAGE_EN_OFFSET         8                    
#define RW_SAME_PAGE_EN_WIDTH          1                    
#define SREFRESH_EXIT_NO_REFRESH_ADDR  36                   
#define SREFRESH_EXIT_NO_REFRESH_OFFSET 24                   
#define SREFRESH_EXIT_NO_REFRESH_WIDTH 1                    
#define START_ADDR                     0                    
#define START_OFFSET                   0                    
#define START_WIDTH                    1                    
#define SWAP_EN_ADDR                   99                   
#define SWAP_EN_OFFSET                 16                   
#define SWAP_EN_WIDTH                  1                    
#define SWLVL_EXIT_ADDR                127                  
#define SWLVL_EXIT_OFFSET              0                    
#define SWLVL_EXIT_WIDTH               1                    
#define SWLVL_LOAD_ADDR                126                  
#define SWLVL_LOAD_OFFSET              16                   
#define SWLVL_LOAD_WIDTH               1                    
#define SWLVL_OP_DONE_ADDR             127                  
#define SWLVL_OP_DONE_OFFSET           8                    
#define SWLVL_OP_DONE_WIDTH            1                    
#define SWLVL_RESP_0_ADDR              127                  
#define SWLVL_RESP_0_OFFSET            16                   
#define SWLVL_RESP_0_WIDTH             1                    
#define SWLVL_RESP_1_ADDR              127                  
#define SWLVL_RESP_1_OFFSET            24                   
#define SWLVL_RESP_1_WIDTH             1                    
#define SWLVL_RESP_2_ADDR              128                  
#define SWLVL_RESP_2_OFFSET            0                    
#define SWLVL_RESP_2_WIDTH             1                    
#define SWLVL_RESP_3_ADDR              128                  
#define SWLVL_RESP_3_OFFSET            8                    
#define SWLVL_RESP_3_WIDTH             1                    
#define SWLVL_START_ADDR               126                  
#define SWLVL_START_OFFSET             24                   
#define SWLVL_START_WIDTH              1                    
#define SW_LEVELING_MODE_ADDR          126                  
#define SW_LEVELING_MODE_OFFSET        8                    
#define SW_LEVELING_MODE_WIDTH         3                    
#define TBST_INT_INTERVAL_ADDR         14                   
#define TBST_INT_INTERVAL_OFFSET       0                    
#define TBST_INT_INTERVAL_WIDTH        3                    
#define TCCD_0_ADDR                    14                   
#define TCCD_0_OFFSET                  8                    
#define TCCD_0_WIDTH                   5                    
#define TCCD_1_ADDR                    17                   
#define TCCD_1_OFFSET                  16                   
#define TCCD_1_WIDTH                   5                    
#define TCKESR_F0_ADDR                 22                   
#define TCKESR_F0_OFFSET               8                    
#define TCKESR_F0_WIDTH                8                    
#define TCKESR_F1_ADDR                 24                   
#define TCKESR_F1_OFFSET               0                    
#define TCKESR_F1_WIDTH                8                    
#define TCKE_F0_ADDR                   22                   
#define TCKE_F0_OFFSET                 0                    
#define TCKE_F0_WIDTH                  3                    
#define TCKE_F1_ADDR                   23                   
#define TCKE_F1_OFFSET                 24                   
#define TCKE_F1_WIDTH                  3                    
#define TDAL_F0_ADDR                   27                   
#define TDAL_F0_OFFSET                 16                   
#define TDAL_F0_WIDTH                  8                    
#define TDAL_F1_ADDR                   27                   
#define TDAL_F1_OFFSET                 24                   
#define TDAL_F1_WIDTH                  8                    
#define TDFI_CTRLUPD_INTERVAL_F0_ADDR  140                  
#define TDFI_CTRLUPD_INTERVAL_F0_OFFSET 0                    
#define TDFI_CTRLUPD_INTERVAL_F0_WIDTH 32                   
#define TDFI_CTRLUPD_INTERVAL_F1_ADDR  145                  
#define TDFI_CTRLUPD_INTERVAL_F1_OFFSET 0                    
#define TDFI_CTRLUPD_INTERVAL_F1_WIDTH 32                   
#define TDFI_CTRLUPD_MAX_F0_ADDR       136                  
#define TDFI_CTRLUPD_MAX_F0_OFFSET     16                   
#define TDFI_CTRLUPD_MAX_F0_WIDTH      16                   
#define TDFI_CTRLUPD_MAX_F1_ADDR       141                  
#define TDFI_CTRLUPD_MAX_F1_OFFSET     16                   
#define TDFI_CTRLUPD_MAX_F1_WIDTH      16                   
#define TDFI_CTRLUPD_MIN_ADDR          136                  
#define TDFI_CTRLUPD_MIN_OFFSET        8                    
#define TDFI_CTRLUPD_MIN_WIDTH         4                    
#define TDFI_CTRL_DELAY_F0_ADDR        146                  
#define TDFI_CTRL_DELAY_F0_OFFSET      16                   
#define TDFI_CTRL_DELAY_F0_WIDTH       4                    
#define TDFI_CTRL_DELAY_F1_ADDR        146                  
#define TDFI_CTRL_DELAY_F1_OFFSET      24                   
#define TDFI_CTRL_DELAY_F1_WIDTH       4                    
#define TDFI_DRAM_CLK_DISABLE_ADDR     147                  
#define TDFI_DRAM_CLK_DISABLE_OFFSET   0                    
#define TDFI_DRAM_CLK_DISABLE_WIDTH    4                    
#define TDFI_DRAM_CLK_ENABLE_ADDR      147                  
#define TDFI_DRAM_CLK_ENABLE_OFFSET    8                    
#define TDFI_DRAM_CLK_ENABLE_WIDTH     4                    
#define TDFI_INIT_COMPLETE_F0_ADDR     52                   
#define TDFI_INIT_COMPLETE_F0_OFFSET   0                    
#define TDFI_INIT_COMPLETE_F0_WIDTH    16                   
#define TDFI_INIT_COMPLETE_F1_ADDR     53                   
#define TDFI_INIT_COMPLETE_F1_OFFSET   0                    
#define TDFI_INIT_COMPLETE_F1_WIDTH    16                   
#define TDFI_INIT_START_F0_ADDR        51                   
#define TDFI_INIT_START_F0_OFFSET      24                   
#define TDFI_INIT_START_F0_WIDTH       8                    
#define TDFI_INIT_START_F1_ADDR        52                   
#define TDFI_INIT_START_F1_OFFSET      16                   
#define TDFI_INIT_START_F1_WIDTH       8                    
#define TDFI_LP_RESP_ADDR              43                   
#define TDFI_LP_RESP_OFFSET            16                   
#define TDFI_LP_RESP_WIDTH             3                    
#define TDFI_PHYUPD_RESP_F0_ADDR       139                  
#define TDFI_PHYUPD_RESP_F0_OFFSET     0                    
#define TDFI_PHYUPD_RESP_F0_WIDTH      16                   
#define TDFI_PHYUPD_RESP_F1_ADDR       144                  
#define TDFI_PHYUPD_RESP_F1_OFFSET     0                    
#define TDFI_PHYUPD_RESP_F1_WIDTH      16                   
#define TDFI_PHYUPD_TYPE0_F0_ADDR      137                  
#define TDFI_PHYUPD_TYPE0_F0_OFFSET    0                    
#define TDFI_PHYUPD_TYPE0_F0_WIDTH     16                   
#define TDFI_PHYUPD_TYPE0_F1_ADDR      142                  
#define TDFI_PHYUPD_TYPE0_F1_OFFSET    0                    
#define TDFI_PHYUPD_TYPE0_F1_WIDTH     16                   
#define TDFI_PHYUPD_TYPE1_F0_ADDR      137                  
#define TDFI_PHYUPD_TYPE1_F0_OFFSET    16                   
#define TDFI_PHYUPD_TYPE1_F0_WIDTH     16                   
#define TDFI_PHYUPD_TYPE1_F1_ADDR      142                  
#define TDFI_PHYUPD_TYPE1_F1_OFFSET    16                   
#define TDFI_PHYUPD_TYPE1_F1_WIDTH     16                   
#define TDFI_PHYUPD_TYPE2_F0_ADDR      138                  
#define TDFI_PHYUPD_TYPE2_F0_OFFSET    0                    
#define TDFI_PHYUPD_TYPE2_F0_WIDTH     16                   
#define TDFI_PHYUPD_TYPE2_F1_ADDR      143                  
#define TDFI_PHYUPD_TYPE2_F1_OFFSET    0                    
#define TDFI_PHYUPD_TYPE2_F1_WIDTH     16                   
#define TDFI_PHYUPD_TYPE3_F0_ADDR      138                  
#define TDFI_PHYUPD_TYPE3_F0_OFFSET    16                   
#define TDFI_PHYUPD_TYPE3_F0_WIDTH     16                   
#define TDFI_PHYUPD_TYPE3_F1_ADDR      143                  
#define TDFI_PHYUPD_TYPE3_F1_OFFSET    16                   
#define TDFI_PHYUPD_TYPE3_F1_WIDTH     16                   
#define TDFI_PHY_RDLAT_F0_ADDR         135                  
#define TDFI_PHY_RDLAT_F0_OFFSET       8                    
#define TDFI_PHY_RDLAT_F0_WIDTH        5                    
#define TDFI_PHY_RDLAT_F1_ADDR         135                  
#define TDFI_PHY_RDLAT_F1_OFFSET       16                   
#define TDFI_PHY_RDLAT_F1_WIDTH        5                    
#define TDFI_PHY_WRDATA_F0_ADDR        153                  
#define TDFI_PHY_WRDATA_F0_OFFSET      16                   
#define TDFI_PHY_WRDATA_F0_WIDTH       3                    
#define TDFI_PHY_WRDATA_F1_ADDR        153                  
#define TDFI_PHY_WRDATA_F1_OFFSET      24                   
#define TDFI_PHY_WRDATA_F1_WIDTH       3                    
#define TDFI_PHY_WRLAT_ADDR            134                  
#define TDFI_PHY_WRLAT_OFFSET          24                   
#define TDFI_PHY_WRLAT_WIDTH           5                    
#define TDFI_RDCSLAT_F0_ADDR           154                  
#define TDFI_RDCSLAT_F0_OFFSET         0                    
#define TDFI_RDCSLAT_F0_WIDTH          5                    
#define TDFI_RDCSLAT_F1_ADDR           154                  
#define TDFI_RDCSLAT_F1_OFFSET         16                   
#define TDFI_RDCSLAT_F1_WIDTH          5                    
#define TDFI_RDDATA_EN_ADDR            135                  
#define TDFI_RDDATA_EN_OFFSET          24                   
#define TDFI_RDDATA_EN_WIDTH           5                    
#define TDFI_RDLVL_EN_ADDR             147                  
#define TDFI_RDLVL_EN_OFFSET           16                   
#define TDFI_RDLVL_EN_WIDTH            8                    
#define TDFI_RDLVL_MAX_ADDR            151                  
#define TDFI_RDLVL_MAX_OFFSET          0                    
#define TDFI_RDLVL_MAX_WIDTH           32                   
#define TDFI_RDLVL_RESP_ADDR           149                  
#define TDFI_RDLVL_RESP_OFFSET         0                    
#define TDFI_RDLVL_RESP_WIDTH          32                   
#define TDFI_RDLVL_RR_ADDR             148                  
#define TDFI_RDLVL_RR_OFFSET           0                    
#define TDFI_RDLVL_RR_WIDTH            10                   
#define TDFI_WRCSLAT_F0_ADDR           154                  
#define TDFI_WRCSLAT_F0_OFFSET         8                    
#define TDFI_WRCSLAT_F0_WIDTH          5                    
#define TDFI_WRCSLAT_F1_ADDR           154                  
#define TDFI_WRCSLAT_F1_OFFSET         24                   
#define TDFI_WRCSLAT_F1_WIDTH          5                    
#define TDLL_ADDR                      12                   
#define TDLL_OFFSET                    8                    
#define TDLL_WIDTH                     16                   
#define TDPD_CNT_DONE_STATUS_ADDR      50                   
#define TDPD_CNT_DONE_STATUS_OFFSET    24                   
#define TDPD_CNT_DONE_STATUS_WIDTH     2                    
#define TDPD_F0_ADDR                   49                   
#define TDPD_F0_OFFSET                 0                    
#define TDPD_F0_WIDTH                  24                   
#define TDPD_F1_ADDR                   50                   
#define TDPD_F1_OFFSET                 0                    
#define TDPD_F1_WIDTH                  24                   
#define TDQSCK_MAX_F0_ADDR             125                  
#define TDQSCK_MAX_F0_OFFSET           8                    
#define TDQSCK_MAX_F0_WIDTH            3                    
#define TDQSCK_MAX_F1_ADDR             125                  
#define TDQSCK_MAX_F1_OFFSET           24                   
#define TDQSCK_MAX_F1_WIDTH            3                    
#define TDQSCK_MIN_F0_ADDR             125                  
#define TDQSCK_MIN_F0_OFFSET           16                   
#define TDQSCK_MIN_F0_WIDTH            2                    
#define TDQSCK_MIN_F1_ADDR             126                  
#define TDQSCK_MIN_F1_OFFSET           0                    
#define TDQSCK_MIN_F1_WIDTH            2                    
#define TFAW_F0_0_ADDR                 15                   
#define TFAW_F0_0_OFFSET               24                   
#define TFAW_F0_0_WIDTH                8                    
#define TFAW_F0_1_ADDR                 19                   
#define TFAW_F0_1_OFFSET               0                    
#define TFAW_F0_1_WIDTH                8                    
#define TFAW_F1_0_ADDR                 17                   
#define TFAW_F1_0_OFFSET               8                    
#define TFAW_F1_0_WIDTH                8                    
#define TFAW_F1_1_ADDR                 20                   
#define TFAW_F1_1_OFFSET               16                   
#define TFAW_F1_1_WIDTH                8                    
#define TINIT3_F0_ADDR                 5                    
#define TINIT3_F0_OFFSET               0                    
#define TINIT3_F0_WIDTH                24                   
#define TINIT3_F1_ADDR                 9                    
#define TINIT3_F1_OFFSET               0                    
#define TINIT3_F1_WIDTH                24                   
#define TINIT4_F0_ADDR                 6                    
#define TINIT4_F0_OFFSET               0                    
#define TINIT4_F0_WIDTH                24                   
#define TINIT4_F1_ADDR                 10                   
#define TINIT4_F1_OFFSET               0                    
#define TINIT4_F1_WIDTH                24                   
#define TINIT5_F0_ADDR                 7                    
#define TINIT5_F0_OFFSET               0                    
#define TINIT5_F0_WIDTH                24                   
#define TINIT5_F1_ADDR                 11                   
#define TINIT5_F1_OFFSET               0                    
#define TINIT5_F1_WIDTH                24                   
#define TINIT_F0_ADDR                  4                    
#define TINIT_F0_OFFSET                0                    
#define TINIT_F0_WIDTH                 24                   
#define TINIT_F1_ADDR                  8                    
#define TINIT_F1_OFFSET                0                    
#define TINIT_F1_WIDTH                 24                   
#define TMOD_F0_ADDR                   21                   
#define TMOD_F0_OFFSET                 8                    
#define TMOD_F0_WIDTH                  8                    
#define TMOD_F1_ADDR                   23                   
#define TMOD_F1_OFFSET                 0                    
#define TMOD_F1_WIDTH                  8                    
#define TMRD_F0_ADDR                   21                   
#define TMRD_F0_OFFSET                 0                    
#define TMRD_F0_WIDTH                  8                    
#define TMRD_F1_ADDR                   22                   
#define TMRD_F1_OFFSET                 24                   
#define TMRD_F1_WIDTH                  8                    
#define TMRR_ADDR                      26                   
#define TMRR_OFFSET                    16                   
#define TMRR_WIDTH                     4                    
#define TPDEX_F0_ADDR                  33                   
#define TPDEX_F0_OFFSET                8                    
#define TPDEX_F0_WIDTH                 16                   
#define TPDEX_F1_ADDR                  34                   
#define TPDEX_F1_OFFSET                0                    
#define TPDEX_F1_WIDTH                 16                   
#define TRAS_LOCKOUT_ADDR              27                   
#define TRAS_LOCKOUT_OFFSET            8                    
#define TRAS_LOCKOUT_WIDTH             1                    
#define TRAS_MAX_F0_ADDR               21                   
#define TRAS_MAX_F0_OFFSET             16                   
#define TRAS_MAX_F0_WIDTH              16                   
#define TRAS_MAX_F1_ADDR               23                   
#define TRAS_MAX_F1_OFFSET             8                    
#define TRAS_MAX_F1_WIDTH              16                   
#define TRAS_MIN_F0_0_ADDR             15                   
#define TRAS_MIN_F0_0_OFFSET           0                    
#define TRAS_MIN_F0_0_WIDTH            8                    
#define TRAS_MIN_F0_1_ADDR             18                   
#define TRAS_MIN_F0_1_OFFSET           8                    
#define TRAS_MIN_F0_1_WIDTH            8                    
#define TRAS_MIN_F1_0_ADDR             16                   
#define TRAS_MIN_F1_0_OFFSET           16                   
#define TRAS_MIN_F1_0_WIDTH            8                    
#define TRAS_MIN_F1_1_ADDR             19                   
#define TRAS_MIN_F1_1_OFFSET           24                   
#define TRAS_MIN_F1_1_WIDTH            8                    
#define TRCD_F0_0_ADDR                 24                   
#define TRCD_F0_0_OFFSET               16                   
#define TRCD_F0_0_WIDTH                8                    
#define TRCD_F0_1_ADDR                 25                   
#define TRCD_F0_1_OFFSET               16                   
#define TRCD_F0_1_WIDTH                8                    
#define TRCD_F1_0_ADDR                 25                   
#define TRCD_F1_0_OFFSET               0                    
#define TRCD_F1_0_WIDTH                8                    
#define TRCD_F1_1_ADDR                 26                   
#define TRCD_F1_1_OFFSET               0                    
#define TRCD_F1_1_WIDTH                8                    
#define TRC_F0_0_ADDR                  14                   
#define TRC_F0_0_OFFSET                24                   
#define TRC_F0_0_WIDTH                 8                    
#define TRC_F0_1_ADDR                  18                   
#define TRC_F0_1_OFFSET                0                    
#define TRC_F0_1_WIDTH                 8                    
#define TRC_F1_0_ADDR                  16                   
#define TRC_F1_0_OFFSET                8                    
#define TRC_F1_0_WIDTH                 8                    
#define TRC_F1_1_ADDR                  19                   
#define TRC_F1_1_OFFSET                16                   
#define TRC_F1_1_WIDTH                 8                    
#define TREF_ENABLE_ADDR               30                   
#define TREF_ENABLE_OFFSET             0                    
#define TREF_ENABLE_WIDTH              1                    
#define TREF_F0_ADDR                   31                   
#define TREF_F0_OFFSET                 0                    
#define TREF_F0_WIDTH                  16                   
#define TREF_F1_ADDR                   32                   
#define TREF_F1_OFFSET                 0                    
#define TREF_F1_WIDTH                  16                   
#define TREF_INTERVAL_ADDR             32                   
#define TREF_INTERVAL_OFFSET           16                   
#define TREF_INTERVAL_WIDTH            16                   
#define TRFC_F0_ADDR                   30                   
#define TRFC_F0_OFFSET                 8                    
#define TRFC_F0_WIDTH                  10                   
#define TRFC_F1_ADDR                   31                   
#define TRFC_F1_OFFSET                 16                   
#define TRFC_F1_WIDTH                  10                   
#define TRP_AB_F0_0_ADDR               28                   
#define TRP_AB_F0_0_OFFSET             8                    
#define TRP_AB_F0_0_WIDTH              8                    
#define TRP_AB_F0_1_ADDR               28                   
#define TRP_AB_F0_1_OFFSET             24                   
#define TRP_AB_F0_1_WIDTH              8                    
#define TRP_AB_F1_0_ADDR               28                   
#define TRP_AB_F1_0_OFFSET             16                   
#define TRP_AB_F1_0_WIDTH              8                    
#define TRP_AB_F1_1_ADDR               29                   
#define TRP_AB_F1_1_OFFSET             0                    
#define TRP_AB_F1_1_WIDTH              8                    
#define TRP_F0_0_ADDR                  15                   
#define TRP_F0_0_OFFSET                16                   
#define TRP_F0_0_WIDTH                 8                    
#define TRP_F0_1_ADDR                  18                   
#define TRP_F0_1_OFFSET                24                   
#define TRP_F0_1_WIDTH                 8                    
#define TRP_F1_0_ADDR                  17                   
#define TRP_F1_0_OFFSET                0                    
#define TRP_F1_0_WIDTH                 8                    
#define TRP_F1_1_ADDR                  20                   
#define TRP_F1_1_OFFSET                8                    
#define TRP_F1_1_WIDTH                 8                    
#define TRRD_F0_0_ADDR                 14                   
#define TRRD_F0_0_OFFSET               16                   
#define TRRD_F0_0_WIDTH                8                    
#define TRRD_F0_1_ADDR                 17                   
#define TRRD_F0_1_OFFSET               24                   
#define TRRD_F0_1_WIDTH                8                    
#define TRRD_F1_0_ADDR                 16                   
#define TRRD_F1_0_OFFSET               0                    
#define TRRD_F1_0_WIDTH                8                    
#define TRRD_F1_1_ADDR                 19                   
#define TRRD_F1_1_OFFSET               8                    
#define TRRD_F1_1_WIDTH                8                    
#define TRTP_F0_ADDR                   20                   
#define TRTP_F0_OFFSET                 24                   
#define TRTP_F0_WIDTH                  8                    
#define TRTP_F1_ADDR                   22                   
#define TRTP_F1_OFFSET                 16                   
#define TRTP_F1_WIDTH                  8                    
#define TWR_F0_0_ADDR                  24                   
#define TWR_F0_0_OFFSET                24                   
#define TWR_F0_0_WIDTH                 6                    
#define TWR_F0_1_ADDR                  25                   
#define TWR_F0_1_OFFSET                24                   
#define TWR_F0_1_WIDTH                 6                    
#define TWR_F1_0_ADDR                  25                   
#define TWR_F1_0_OFFSET                8                    
#define TWR_F1_0_WIDTH                 6                    
#define TWR_F1_1_ADDR                  26                   
#define TWR_F1_1_OFFSET                8                    
#define TWR_F1_1_WIDTH                 6                    
#define TWTR_F0_0_ADDR                 15                   
#define TWTR_F0_0_OFFSET               8                    
#define TWTR_F0_0_WIDTH                6                    
#define TWTR_F0_1_ADDR                 18                   
#define TWTR_F0_1_OFFSET               16                   
#define TWTR_F0_1_WIDTH                6                    
#define TWTR_F1_0_ADDR                 16                   
#define TWTR_F1_0_OFFSET               24                   
#define TWTR_F1_0_WIDTH                6                    
#define TWTR_F1_1_ADDR                 20                   
#define TWTR_F1_1_OFFSET               0                    
#define TWTR_F1_1_WIDTH                6                    
#define TXSNR_F0_ADDR                  35                   
#define TXSNR_F0_OFFSET                0                    
#define TXSNR_F0_WIDTH                 16                   
#define TXSNR_F1_ADDR                  36                   
#define TXSNR_F1_OFFSET                0                    
#define TXSNR_F1_WIDTH                 16                   
#define TXSR_F0_ADDR                   34                   
#define TXSR_F0_OFFSET                 16                   
#define TXSR_F0_WIDTH                  16                   
#define TXSR_F1_ADDR                   35                   
#define TXSR_F1_OFFSET                 16                   
#define TXSR_F1_WIDTH                  16                   
#define UPDATE_ERROR_STATUS_ADDR       135                  
#define UPDATE_ERROR_STATUS_OFFSET     0                    
#define UPDATE_ERROR_STATUS_WIDTH      7                    
#define VERSION_ADDR                   0                    
#define VERSION_OFFSET                 16                   
#define VERSION_WIDTH                  16                   
#define W2R_DIFFCS_DLY_F0_ADDR         122                  
#define W2R_DIFFCS_DLY_F0_OFFSET       16                   
#define W2R_DIFFCS_DLY_F0_WIDTH        5                    
#define W2R_DIFFCS_DLY_F1_ADDR         123                  
#define W2R_DIFFCS_DLY_F1_OFFSET       16                   
#define W2R_DIFFCS_DLY_F1_WIDTH        5                    
#define W2R_SAMECS_DLY_ADDR            124                  
#define W2R_SAMECS_DLY_OFFSET          24                   
#define W2R_SAMECS_DLY_WIDTH           5                    
#define W2R_SPLIT_EN_ADDR              98                   
#define W2R_SPLIT_EN_OFFSET            24                   
#define W2R_SPLIT_EN_WIDTH             1                    
#define W2W_DIFFCS_DLY_F0_ADDR         122                  
#define W2W_DIFFCS_DLY_F0_OFFSET       24                   
#define W2W_DIFFCS_DLY_F0_WIDTH        5                    
#define W2W_DIFFCS_DLY_F1_ADDR         123                  
#define W2W_DIFFCS_DLY_F1_OFFSET       24                   
#define W2W_DIFFCS_DLY_F1_WIDTH        5                    
#define W2W_SAMECS_DLY_ADDR            125                  
#define W2W_SAMECS_DLY_OFFSET          0                    
#define W2W_SAMECS_DLY_WIDTH           5                    
#define WRITEINTERP_ADDR               24                   
#define WRITEINTERP_OFFSET             8                    
#define WRITEINTERP_WIDTH              1                    
#define WRITE_DATA_FIFO_DEPTH_ADDR     1                    
#define WRITE_DATA_FIFO_DEPTH_OFFSET   24                   
#define WRITE_DATA_FIFO_DEPTH_WIDTH    8                    
#define WRITE_DATA_FIFO_PTR_WIDTH_ADDR 2                    
#define WRITE_DATA_FIFO_PTR_WIDTH_OFFSET 0                    
#define WRITE_DATA_FIFO_PTR_WIDTH_WIDTH 8                    
#define WRITE_MODEREG_ADDR             58                   
#define WRITE_MODEREG_OFFSET           0                    
#define WRITE_MODEREG_WIDTH            27                   
#define WRLAT_ADJ_F0_ADDR              141                  
#define WRLAT_ADJ_F0_OFFSET            8                    
#define WRLAT_ADJ_F0_WIDTH             5                    
#define WRLAT_ADJ_F1_ADDR              146                  
#define WRLAT_ADJ_F1_OFFSET            8                    
#define WRLAT_ADJ_F1_WIDTH             5                    
#define WRLAT_F0_ADDR                  13                   
#define WRLAT_F0_OFFSET                8                    
#define WRLAT_F0_WIDTH                 3                    
#define WRLAT_F1_ADDR                  13                   
#define WRLAT_F1_OFFSET                24                   
#define WRLAT_F1_WIDTH                 3                    
#define WR_ORDER_REQ_ADDR              101                  
#define WR_ORDER_REQ_OFFSET            16                   
#define WR_ORDER_REQ_WIDTH             2                    
#define ZQCL_F0_ADDR                   85                   
#define ZQCL_F0_OFFSET                 16                   
#define ZQCL_F0_WIDTH                  12                   
#define ZQCL_F1_ADDR                   87                   
#define ZQCL_F1_OFFSET                 0                    
#define ZQCL_F1_WIDTH                  12                   
#define ZQCS_F0_ADDR                   86                   
#define ZQCS_F0_OFFSET                 0                    
#define ZQCS_F0_WIDTH                  12                   
#define ZQCS_F1_ADDR                   87                   
#define ZQCS_F1_OFFSET                 16                   
#define ZQCS_F1_WIDTH                  12                   
#define ZQCS_ROTATE_ADDR               91                   
#define ZQCS_ROTATE_OFFSET             24                   
#define ZQCS_ROTATE_WIDTH              1                    
#define ZQINIT_F0_ADDR                 85                   
#define ZQINIT_F0_OFFSET               0                    
#define ZQINIT_F0_WIDTH                12                   
#define ZQINIT_F1_ADDR                 86                   
#define ZQINIT_F1_OFFSET               16                   
#define ZQINIT_F1_WIDTH                12                   
#define ZQRESET_F0_ADDR                90                   
#define ZQRESET_F0_OFFSET              8                    
#define ZQRESET_F0_WIDTH               12                   
#define ZQRESET_F1_ADDR                91                   
#define ZQRESET_F1_OFFSET              0                    
#define ZQRESET_F1_WIDTH               12                   
#define ZQ_INTERVAL_ADDR               89                   
#define ZQ_INTERVAL_OFFSET             0                    
#define ZQ_INTERVAL_WIDTH              32                   
#define ZQ_IN_PROGRESS_ADDR            90                   
#define ZQ_IN_PROGRESS_OFFSET          0                    
#define ZQ_IN_PROGRESS_WIDTH           1                    
#define ZQ_ON_SREF_EXIT_ADDR           88                   
#define ZQ_ON_SREF_EXIT_OFFSET         8                    
#define ZQ_ON_SREF_EXIT_WIDTH          4                    
#define ZQ_REQ_ADDR                    88                   
#define ZQ_REQ_OFFSET                  0                    
#define ZQ_REQ_WIDTH                   4     

// DDR PHY register map
#define DDRPHY_DQ_TIMING_REG_0              0x00000000
#define DDRPHY_DQS_TIMING_REG_0             0x00000004
#define DDRPHY_GATE_LPBK_CTRL_REG_0         0x00000008
#define DDRPHY_READ_CTRL_REG_0              0x0000000c
#define DDRPHY_DLL_MASTER_CTRL_REG_0        0x00000010
#define DDRPHY_DLL_SLAVE_CTRL_REG_0         0x00000014
#define DDRPHY_DEN_PHY_OBS_REG_0_0          0x00000018
#define DDRPHY_DLL_OBS_REG_0_0              0x0000001c
#define DDRPHY_DLL_OBS_REG_1_0              0x00000020
#define DDRPHY_DLL_OBS_REG_2_0              0x00000024
#define DDRPHY_LVL_DBG_CONT_REG_0           0x00000028
#define DDRPHY_LVL_CONFIG_REG_0             0x0000002c
#define DDRPHY_GTLVL_OBS_REG_0              0x00000030
#define DDRPHY_RDLVL_OBS_REG_0              0x00000034
#define DDRPHY_WRLVL_CONFIG_REG_0           0x00000038
#define DDRPHY_WRLVL_OBS_REG_0              0x0000003c
#define DDRPHY_DQ_TIMING_REG_1              0x00000040
#define DDRPHY_DQS_TIMING_REG_1             0x00000044
#define DDRPHY_GATE_LPBK_CTRL_REG_1         0x00000048
#define DDRPHY_READ_CTRL_REG_1              0x0000004c
#define DDRPHY_DLL_MASTER_CTRL_REG_1        0x00000050
#define DDRPHY_DLL_SLAVE_CTRL_REG_1         0x00000054
#define DDRPHY_DEN_PHY_OBS_REG_0_1          0x00000058
#define DDRPHY_DLL_OBS_REG_0_1              0x0000005c
#define DDRPHY_DLL_OBS_REG_1_1              0x00000060
#define DDRPHY_DLL_OBS_REG_2_1              0x00000064
#define DDRPHY_LVL_DBG_CONT_REG_1           0x00000068
#define DDRPHY_LVL_CONFIG_REG_1             0x0000006c
#define DDRPHY_GTLVL_OBS_REG_1              0x00000070
#define DDRPHY_RDLVL_OBS_REG_1              0x00000074
#define DDRPHY_WRLVL_CONFIG_REG_1           0x00000078
#define DDRPHY_WRLVL_OBS_REG_1              0x0000007c
#define DDRPHY_DQ_TIMING_REG_2              0x00000080
#define DDRPHY_DQS_TIMING_REG_2             0x00000084
#define DDRPHY_GATE_LPBK_CTRL_REG_2         0x00000088
#define DDRPHY_READ_CTRL_REG_2              0x0000008c
#define DDRPHY_DLL_MASTER_CTRL_REG_2        0x00000090
#define DDRPHY_DLL_SLAVE_CTRL_REG_2         0x00000094
#define DDRPHY_DEN_PHY_OBS_REG_0_2          0x00000098
#define DDRPHY_DLL_OBS_REG_0_2              0x0000009c
#define DDRPHY_DLL_OBS_REG_1_2              0x000000a0
#define DDRPHY_DLL_OBS_REG_2_2              0x000000a4
#define DDRPHY_LVL_DBG_CONT_REG_2           0x000000a8
#define DDRPHY_LVL_CONFIG_REG_2             0x000000ac
#define DDRPHY_GTLVL_OBS_REG_2              0x000000b0
#define DDRPHY_RDLVL_OBS_REG_2              0x000000b4
#define DDRPHY_WRLVL_CONFIG_REG_2           0x000000b8
#define DDRPHY_WRLVL_OBS_REG_2              0x000000bc
#define DDRPHY_DEN_PHY_DQ_TIMING_REG_3      0x000000c0
#define DDRPHY_DEN_PHY_DQS_TIMING_REG_3     0x000000c4
#define DDRPHY_DEN_PHY_GATE_LPBK_CTRL_REG_3 0x000000c8
#define DDRPHY_DEN_PHY_READ_CTRL_REG_3      0x000000cc
#define DDRPHY_DLL_MASTER_CTRL_REG_3        0x000000d0
#define DDRPHY_DLL_SLAVE_CTRL_REG_3         0x000000d4
#define DDRPHY_DEN_PHY_OBS_REG_0_3          0x000000d8
#define DDRPHY_DLL_OBS_REG_0_3              0x000000dc
#define DDRPHY_DLL_OBS_REG_1_3              0x000000e0
#define DDRPHY_DLL_OBS_REG_2_3              0x000000e4
#define DDRPHY_LVL_DBG_CONT_REG_3           0x000000e8
#define DDRPHY_LVL_CONFIG_REG_3             0x000000ec
#define DDRPHY_GTLVL_OBS_REG_3              0x000000f0
#define DDRPHY_RDLVL_OBS_REG_3              0x000000f4
#define DDRPHY_WRLVL_CONFIG_REG_3           0x000000f8
#define DDRPHY_WRLVL_OBS_REG_3              0x000000fc
#define DDRPHY_DEN_PHY_DQ_TIMING_REG_4      0x00000100
#define DDRPHY_DEN_PHY_DQS_TIMING_REG_4     0x00000104
#define DDRPHY_DEN_PHY_GATE_LPBK_CTRL_REG_4 0x00000108
#define DDRPHY_DEN_PHY_READ_CTRL_REG_4      0x0000010c
#define DDRPHY_DLL_MASTER_CTRL_REG_4        0x00000110
#define DDRPHY_DLL_SLAVE_CTRL_REG_4         0x00000114
#define DDRPHY_DEN_PHY_OBS_REG_0_4          0x00000118
#define DDRPHY_DLL_OBS_REG_0_4              0x0000011c
#define DDRPHY_DLL_OBS_REG_1_4              0x00000120
#define DDRPHY_DLL_OBS_REG_2_4              0x00000124
#define DDRPHY_LVL_DBG_CONT_REG_4           0x00000128
#define DDRPHY_LVL_CONFIG_REG_4             0x0000012c
#define DDRPHY_GTLVL_OBS_REG_4              0x00000130
#define DDRPHY_RDLVL_OBS_REG_4              0x00000134
#define DDRPHY_WRLVL_CONFIG_REG_4           0x00000138
#define DDRPHY_WRLVL_OBS_REG_4              0x0000013c
#define DDRPHY_DEN_PHY_CTRL_REG             0x00000000
#define DDRPHY_DEN_PHY_CALVL_DEBUG_STEP_REG 0x00000004
#define DDRPHY_DEN_PHY_CALVL_CTRL_REG       0x00000008
#define DDRPHY_DEN_PHY_CALVL_OBS_REG        0x0000000c
#define DDRPHY_DEN_PHY_LP_WAKEUP_REG        0x00000010
#define DDRPHY_DEN_PHY_PAD_TSEL_REG         0x00000014

// DDR Controller register map

// Define DDR clock
typedef enum
{
	DDR_CLK_100MHZ	= 0,
	DDR_CLK_133MHZ	= 1,
	DDR_CLK_200MHZ	= 2,
	DDR_CLK_400MHZ	= 3,
	DDR_CLK_533MHZ	= 4
}E_DDR1_CLK;

// Define DDR scramble
typedef enum
{
	DDR_SCRAM_DIS	= 0,
	DDR_SCRAM_EN	= 1,
	DDR_SCRAM_CNT	= 2
}E_DDR_SCRAM;

// Define DDR configure
typedef enum
{
	// LPDDR
	LPDDR_CONFIG_100MHZ_CL3_BL8		= 0,
	LPDDR_CONFIG_133MHZ_CL3_BL4		= 1,
	LPDDR_CONFIG_133MHZ_CL3_BL8		= 2,
	LPDDR_CONFIG_200MHZ_CL3_BL4		= 3,
	LPDDR_CONFIG_200MHZ_CL3_BL8		= 4,

	// LPDDR2
	LPDDR2_CONFIG_133MHZ_CL3_BL4	= 5,
	LPDDR2_CONFIG_133MHZ_CL3_BL8	= 6,
	LPDDR2_CONFIG_200MHZ_CL3_BL4	= 7,
	LPDDR2_CONFIG_200MHZ_CL3_BL8	= 8,
	LPDDR2_CONFIG_400MHZ_CL6_BL4	= 9,
	LPDDR2_CONFIG_400MHZ_CL6_BL8	= 10,
	LPDDR2_CONFIG_533MHZ_CL8_BL4	= 11,
	LPDDR2_CONFIG_533MHZ_CL8_BL8	= 12,
	LPDDR2_CONFIG_CNT				= 13
}E_DDR_CONFIG;

// Define DDR scan mode
typedef enum
{
	DDR_SCAN_MODE_0X00	= 0,
	DDR_SCAN_MODE_0XFF	= 1,
	DDR_SCAN_MODE_0XAA	= 2,
	DDR_SCAN_MODE_0X55	= 3,
	DDR_SCAN_MODE_RAND	= 4,
	DDR_SCAN_MODE_CNT	= 5
}E_DDR_SCAN_MODE;

/*************************************************************************************************************/
// structure definition
/*************************************************************************************************************/
// Define DDR Controller structure 
struct brite_ddr_ctrl {
	void *regs;
};

// Define DDR PHY structure 
struct brite_ddr_phy {
	void *regs;
};

/*************************************************************************************************************/
// global variable declaration
/*************************************************************************************************************/
extern struct brite_ddr_ctrl *p_ddr_ctrl;
extern struct brite_ddr_phy *p_ddr_phy;

extern struct brite_clk_pll *p_pll;

/*************************************************************************************************************/
// function prototype declaration
/*************************************************************************************************************/
int ddr_init_0(E_DDR_CONFIG ddr_cfg, E_DDR_SCRAM scram_mode);

int ddr_scan(uint32_t scan_data, uint32_t scan_size);

#endif

